### ISSUE TITLE
How did you resume execution context?

### ISSUE THREAD

**Issue by linonetwo** [n-riesco/nel#14]
As I know, a code block in Jupyter Notebook can use variable value from other block, how is this implemented in the nel?

I'm reading the code, consider how to embed nel into https://github.com/Jermolene/TiddlyWiki5 . Can you teach me a bit about the source code?

**Comment by n-riesco** [comment]
> As I know, a code block in Jupyter Notebook can use variable value from other block, how is this implemented in the nel?

This is how. NEL spawns a Node.js session as a [ChildProcess](https://nodejs.org/api/child_process.html#class-childprocess) here:

https://github.com/n-riesco/nel/blob/9dfd47f15d8be83ee1e313d512a34180c99003c9/lib/nel.js#L174-L210

And to process an execution request, NEL sends a message to the `ChildProcess` here:

https://github.com/n-riesco/nel/blob/9dfd47f15d8be83ee1e313d512a34180c99003c9/lib/nel.js#L866-L916

The `ChildProcess` receives the message here:

https://github.com/n-riesco/nel/blob/9dfd47f15d8be83ee1e313d512a34180c99003c9/lib/server/main.js#L94-L124

And the execution request in the `ChildProcess` is implemented via `vm.runInThisContext` here:

https://github.com/n-riesco/nel/blob/9dfd47f15d8be83ee1e313d512a34180c99003c9/lib/server/main.js#L316-L318

> I'm reading the code, consider how to embed nel into https://github.com/Jermolene/TiddlyWiki5 . Can you teach me a bit about the source code?

Sure, I'm happy to help.

**Comment by linonetwo** [comment]
Thank you, Riesco, I may be clear about this now!

userside -> nel -> child\_process spawn server/main.js, for each notebook (I thought it is for each code block, so I was confused about how context is maintained)

When a user keeps his notebook open, the `_done` will always be `false`. So when the second and third code blocks are added into the notebook and gets executed, the code will get access to variables defined in the `global` (due to `vm.runInThisContext(code)`) by the first code block.

**Comment by linonetwo** [comment]
For short, "variable value from other block" are stored inside the `global` of the child\_process.

So they are not serializable, when opening a new notebook, you can't directly execute 3rd code block, you can see the cached output, but need to execute from the first to the third!

I think this applied to the IPython too.

The thing that differs from IPython is, in nodejs we have `let` and `const` that will prevent a block to execute on the same `global` for 2 times. So we have to use `var` in the notebook! Is this correct?

**Comment by n-riesco** [comment]
Ummm... I'm afraid my choice of name for [Context](https://github.com/n-riesco/nel/blob/9dfd47f15d8be83ee1e313d512a34180c99003c9/lib/server/context.js) is confusing.

In NEL, a [Context](https://github.com/n-riesco/nel/blob/9dfd47f15d8be83ee1e313d512a34180c99003c9/lib/server/context.js) represents the `stdout`, `stderr`, `stdin` and the execution result of a Jupyter execution request. It's not a JavaScript execution context. A NEL [Context](https://github.com/n-riesco/nel/blob/9dfd47f15d8be83ee1e313d512a34180c99003c9/lib/server/context.js) provides support for asynchronous execution requests. See [here](http://n-riesco.github.io/ijavascript/doc/async.ipynb.html).

> userside -> nel -> child_process spawn server/main.js, for each notebook (I thought it is for each code block, so I was confused about how context is maintained)

Correct.

> When a user keeps his notebook open, the `_done` will always be false. 

No, `_done` is used to support [asynchronous execution requests](http://n-riesco.github.io/ijavascript/doc/async.ipynb.html).

> So when the second and third code blocks are added into the notebook and gets executed, the code will get access to variables defined in the global (due to vm.runInThisContext(code)) by the first code block.
>
> For short, "variable value from other block" are stored inside the global of the child_process.

Correct.

> So they are not serializable, when opening a new notebook, you can't directly execute 3rd code block, you can see the cached output, but need to execute from the first to the third!
>
> I think this applied to the IPython too.

Correct, each notebook launches a new instance of the kernel. Although, strictly speaking, this depends on the client you're using. If I remember correctly, [Hydrogen](https://github.com/nteract/hydrogen) shares the same kernel for all the files opened for a given language.

> The thing that differs from IPython is, in nodejs we have let and const that will prevent a block to execute on the same global for 2 times. So we have to use var in the notebook! Is this correct?

By design, the IJavascript kernel behaves as the Node.js CLI does. This design decision can be changed (usually by parsing the execution request and transforming as wished), see [ijavascript-await](https://www.npmjs.com/package/ijavascript-await) for an example. If/when Node.js changes its behaviour with `const`, `let`, and `await` (usually after V8 does), then IJavascript will inherit the changes.
